---
- hosts: machines
  tasks:
    - name: Install Docker
      apt: pkg=docker.io state=installed update_cache=true
      notify:
        - Restart Docker

  handlers:
    - name: Restart Docker
      shell: gpasswd -a ${USER} docker && service docker restart
      become: true
      notify:
        - Reboot Server

    - name: Reboot Server
      command: /sbin/reboot
