---
- hosts: machines
  tasks:
    - name: Install JDK
      apt: pkg=openjdk-8-jdk state=installed update_cache=true
      become: true

    - name: Install nginx
      apt: pkg=nginx state=installed
      notify:
        - Start Nginx

    - name: Add key
      become: true
      apt_key:
        url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
        state: present
      register: keyadded
     
    - name: Add Repo
      become: true
      command: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
      register: repoadded 
    
    - name: Install Jenkins
      when: keyadded|success and repoadded|success
      apt:
        update_cache: yes
        name: jenkins
        force: yes
      become: true

  handlers:
    - name: Start Nginx
      service: name=nginx state=started
