---
- hosts: Jenkins_slaves
  become: true
  tasks:
    - name: Install Default JRE Debian Based
      apt:
        pkg: default-jre
        state: installed
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install Default JRE on Red Hat Based
      dnf:
        name: java-1.8.0-openjdk
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Create workspace on slave
      file: path={{ workspace_path }} state=directory

    - name: Change owner of the directory
      file:
        path: '{{ workspace_path }}'
        owner: '{{ owner }}'
        group: '{{ group }}'
    
    - name: Install extra packages on debian based
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - git
        - python
        - python3
        - gcc
        - make
      when: ansible_os_family == "Debian"

    - name: Install extra packages on Red Hat based
      dnf: name={{ item }} state=latest
      with_items:
        - git
        - python
        - python3
        - gcc
        - make
      when: ansible_os_family == "RedHat"
