---
- hosts: Jenkins_slaves
  tasks:
    - name: Install Default JRE Debian Based
      apt:
        pkg: default-jre
        state: installed
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Install Default JRE on Red Hat Based
      dnf:
        name: default-jre
        state: latest
      become: true
      when: ansible_os_family == "RedHat"

    - name: Create workspace on slave
      file: path={{ workspace_path }} state=directory
      become: true

    - name: Change owner of the directory
      become: true
      file:
        path: '{{ workspace_path }}'
        owner: '{{ owner }}'
        group: '{{ group }}'
    
    - name: Install Packages
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - git
        - python
        - python3
        - gcc
        - make
      become: true
      when: ansible_os_family == "Debian"
